env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin

sudo: true

os:
  - linux
  - osx

osx_image: xcode8.2

compiler:
  - gcc
  - clang

language: node_js

node_js:
  - "7"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  cargo: true
  directories:
    - node_modules

before_install:
  - curl -s https://static.rust-lang.org/rustup.sh | sudo sh
  - "[[ ${TRAVIS_OS_NAME} = linux ]] && export CXX=g++-4.8 || echo 'skipped'"

install:
  - node --version
  - npm --version
  - ls $TRAVIS_BUILD_DIR
  - npm i

before_script:
  - npm run grep-error-codes

script:
  - npm run lint
  - npm test
