sudo: false

matrix:
  include:
  - os: linux
  - os: osx

language: generic

osx_image: xcode7.3

cache:
  directories:
    - node_modules

addons:
  apt:
    packages:
      - xvfb

install:
  - export CXX="g++-4.8"
  - nvm --version
  - nvm install 6.9.1
  - node --version
  - npm --version
  - npm i

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sleep 3

script:
  - npm run lint
  - npm run test