sudo: false

matrix:
  include:
  - os: osx

language: node_js

node_js:
  - "6"

cache:
  directories:
    - node_modules

install:
  - nvm --version
  - nvm install 6.9.1
  - node --version
  - npm --version
  - npm i

before_script:
  - sh -e /etc/init.d/xvfb start &
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sleep 3

script:
  - npm run lint
  - npm run test