environment:
  nodejs_version: "6.9.1"

platform:
  - x86
  - x64

cache:
  - node_modules

matrix:
  fast_finish: true

clone_depth: 50

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version
  - npm --version
  - npm i

build: off

test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm test

