environment:
  nodejs_version: "6.9.1"
  global:
    RUST_BACKTRACE: 1
  matrix:
    - RUST_VERSION: 1.14.0

platform:
  - x86
  - x64

cache:
  - node_modules

matrix:
  fast_finish: true

clone_depth: 50

configuration:
  - Release

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version
  - npm --version
  - ps: |
          $url = "https://github.com/maidsafe/QA/raw/master/Powershell%20Scripts/AppVeyor"
          cmd /c curl -fsSL -o "Install Rustup.ps1" "$url/Install%20Rustup.ps1"
          . ".\Install Rustup.ps1"
  - ps: cd $env:APPVEYOR_BUILD_FOLDER
  - git submodule update --init --recursive
  - npm i

build: off

before_test:
  - npm run release:mock
  - npm run copy-binaries:win
  - npm run grep-error-codes
  - ps: |
          if($env:platform -eq "x86") {
            Copy-Item C:\Logfiles -Destination C:\Drawings -Recurse C:\MinGW\bin\libwinpthread-1.dll $env:APPVEYOR_BUILD_FOLDER\src\ffi -Force
          } Else {
            Copy-Item C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin\libwinpthread-1.dll $env:APPVEYOR_BUILD_FOLDER\src\ffi -Force
          }
  - ps: ls $env:APPVEYOR_BUILD_FOLDER\src\ffi

test_script:
  - npm run lint
  - npm test
